# Generated by Django 4.0.4 on 2022-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktype',
            name='salary_type',
        ),
        migrations.AddField(
            model_name='employee',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeSalaryType',
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
