# Generated by Django 4.0.4 on 2022-04-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_worktype_salary_type_employee_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='fee',
        ),
        migrations.CreateModel(
            name='EmployeeFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.employee')),
                ('order_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.orderdetail')),
            ],
        ),
    ]
