# Generated by Django 4.0.4 on 2022-04-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_employee_fee_employeefee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.CharField(choices=[('ماهوار', 'ماهوار'), ('کونترات', 'کونترات')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
