# Generated by Django 4.0.4 on 2022-04-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_orderdetail_employee_orderdetail_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='with_color',
            field=models.CharField(blank=True, choices=[('بلی', 'بلی'), ('نخیر', 'نخیر')], max_length=20, null=True),
        ),
    ]
