# Generated by Django 4.0.4 on 2022-04-20 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_orderdetail_with_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
