# Generated by Django 4.0.4 on 2022-04-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_orderdetail_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefee',
            name='get_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
