# Generated by Django 4.0.4 on 2022-04-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_employeefee_get_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefee',
            name='remain_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='employeefee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
