# Generated by Django 4.0.4 on 2022-04-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_employeefee_remain_amount_employeefee_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
