# Generated by Django 4.0.4 on 2022-04-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_expensecategory_income_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='exp_date',
            field=models.DateTimeField(),
        ),
    ]
