# Generated by Django 4.0.4 on 2022-04-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_expense_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='exp_date',
            field=models.DateField(),
        ),
    ]
