# Generated by Django 4.0.4 on 2022-04-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_expense_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='exp_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='expense',
            name='from_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='good_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='rant_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='to_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
