# Generated by Django 4.0.4 on 2022-04-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_expense_exp_quantity_expense_from_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='alternative',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rant_month',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
