# Generated by Django 4.0.4 on 2022-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_income_alternative_income_amount_income_income_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
