# Generated by Django 4.0.4 on 2022-05-03 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_exhibition_alter_customer_add_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
