# Generated by Django 4.0.4 on 2022-05-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_customer_add_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='options',
            field=models.CharField(blank=True, choices=[('بلی', 'بلی'), ('نخیر', 'نخیر')], default='نخیر', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='unit',
            field=models.CharField(blank=True, choices=[('عدد', 'عدد'), ('متر', 'متر')], default='عدد', max_length=10, null=True),
        ),
    ]
