# Generated by Django 4.0.4 on 2022-05-07 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_orderdetail_options_orderdetail_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='options',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='unit',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
