# Generated by Django 4.0.4 on 2022-05-08 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_orderdetail_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='description',
        ),
        migrations.AddField(
            model_name='recieve',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recieve',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
